name: Create Random GIFs

on:
  schedule:
    - cron: "0 3 1 * *"
    - cron: "0 3 15 * *"

permissions:
    contents: write

jobs:
  create_random_gifs:
    runs-on: ubuntu-latest
    env:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        repo_user: "T3l3sc0p3"
        repo_name: "CDN-for-personal-use"
        branch: "Kuriyama-Mirai"
        directory: "gifs"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.12'
            check-latest: true
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install requests pyyaml

      - name: Create random gifs
        run: |
            python ".github/script/random_gif.py" "README.md"
            git config --local user.name "github-actions[bot]"
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "Create random GIFs"
            git push
